[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mloader"
version = "0.1.0"
description = "Your Mloader description"
readme = "README.md"
license = {text = "MIT"}   # or your license
authors = [
    {name = "Nathan Kuipa", email = "nathankuipa44@email.com"}
]
dependencies = []          # add your dependencies, e.g. ["requests>=2.0"]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/nathankuipa25/Mloader"
Repository = "https://github.com/nathankuipa25/Mloader.git"

# Optional: tell setuptools where to find packages (default works)
[tool.setuptools.packages.find]
where = ["."]              # searches in the current directory